# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kacperfilipiakprivate/Projects/University/SO2_rail_simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kacperfilipiakprivate/Projects/University/SO2_rail_simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kacperfilipiakprivate/Projects/University/SO2_rail_simulator/CMakeFiles /Users/kacperfilipiakprivate/Projects/University/SO2_rail_simulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kacperfilipiakprivate/Projects/University/SO2_rail_simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main_app

# Build rule for target.
main_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_app
.PHONY : main_app

# fast build rule for target.
main_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/build
.PHONY : main_app/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/main.cpp.s
.PHONY : main.cpp.s

src/city.o: src/city.cpp.o
.PHONY : src/city.o

# target to build an object file
src/city.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/city.cpp.o
.PHONY : src/city.cpp.o

src/city.i: src/city.cpp.i
.PHONY : src/city.i

# target to preprocess a source file
src/city.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/city.cpp.i
.PHONY : src/city.cpp.i

src/city.s: src/city.cpp.s
.PHONY : src/city.s

# target to generate assembly for a file
src/city.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/city.cpp.s
.PHONY : src/city.cpp.s

src/connectionmatrix.o: src/connectionmatrix.cpp.o
.PHONY : src/connectionmatrix.o

# target to build an object file
src/connectionmatrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/connectionmatrix.cpp.o
.PHONY : src/connectionmatrix.cpp.o

src/connectionmatrix.i: src/connectionmatrix.cpp.i
.PHONY : src/connectionmatrix.i

# target to preprocess a source file
src/connectionmatrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/connectionmatrix.cpp.i
.PHONY : src/connectionmatrix.cpp.i

src/connectionmatrix.s: src/connectionmatrix.cpp.s
.PHONY : src/connectionmatrix.s

# target to generate assembly for a file
src/connectionmatrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/connectionmatrix.cpp.s
.PHONY : src/connectionmatrix.cpp.s

src/railway.o: src/railway.cpp.o
.PHONY : src/railway.o

# target to build an object file
src/railway.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/railway.cpp.o
.PHONY : src/railway.cpp.o

src/railway.i: src/railway.cpp.i
.PHONY : src/railway.i

# target to preprocess a source file
src/railway.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/railway.cpp.i
.PHONY : src/railway.cpp.i

src/railway.s: src/railway.cpp.s
.PHONY : src/railway.s

# target to generate assembly for a file
src/railway.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/railway.cpp.s
.PHONY : src/railway.cpp.s

src/train.o: src/train.cpp.o
.PHONY : src/train.o

# target to build an object file
src/train.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/train.cpp.o
.PHONY : src/train.cpp.o

src/train.i: src/train.cpp.i
.PHONY : src/train.i

# target to preprocess a source file
src/train.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/train.cpp.i
.PHONY : src/train.cpp.i

src/train.s: src/train.cpp.s
.PHONY : src/train.s

# target to generate assembly for a file
src/train.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_app.dir/build.make CMakeFiles/main_app.dir/src/train.cpp.s
.PHONY : src/train.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main_app"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/city.o"
	@echo "... src/city.i"
	@echo "... src/city.s"
	@echo "... src/connectionmatrix.o"
	@echo "... src/connectionmatrix.i"
	@echo "... src/connectionmatrix.s"
	@echo "... src/railway.o"
	@echo "... src/railway.i"
	@echo "... src/railway.s"
	@echo "... src/train.o"
	@echo "... src/train.i"
	@echo "... src/train.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

